# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import getaddr, refresh, mandatx
import subprocess

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 320)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 50, 111, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 120, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(30, 50, 171, 22))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(230, 50, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 160, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 190, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(170, 160, 16, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(170, 190, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(330, 190, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 520, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.label_ok = QtWidgets.QLabel(self.centralwidget)
        self.label_ok.setGeometry(QtCore.QRect(30, 230, 471, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ok.setFont(font)
        self.label_ok.setObjectName("label_ok")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        #pushButton = get new address
        #pushButton2 = refresh
        #pushButton3= copia
        #pushButton4= send
        self.pushButton.setText(_translate("MainWindow", "Get new address"))
        self.pushButton_2.setText(_translate("MainWindow", "Refresh"))
        self.label.setText(_translate("MainWindow", "Your address(es):"))
        self.pushButton_3.setText(_translate("MainWindow", "Copy"))
        self.label_2.setText(_translate("MainWindow", "Your ScarletCoins"))
        self.label_3.setText(_translate("MainWindow", "1234567890"))
        self.label_4.setText(_translate("MainWindow", "Send"))
        self.lineEdit.setText(_translate("MainWindow", "12345"))
        self.label_5.setText(_translate("MainWindow", "to"))
        self.lineEdit_2.setText(_translate("MainWindow", "abcdef123"))
        self.pushButton_4.setText(_translate("MainWindow", "Send"))

        self.label_ok.setText(_translate("MainWindow", ""))

        self.pushButton.clicked.connect(self.ga)
        self.pushButton_2.clicked.connect(self.ref)
        self.pushButton_4.clicked.connect(self.send)
        self.pushButton_3.clicked.connect(self.copia)

        with open('data/addresslist.txt', 'r') as f:
            addresses=f.readlines()
        for l in addresses:
            appendi=l[:16]
            self.comboBox.addItem(appendi)
        
        #print(self.comboBox.currentText())

        actualaddress=self.comboBox.currentText()
        actualcoins=refresh.ref(actualaddress)
        self.label_3.setText(str(actualcoins))

    def copia(self):
        actualaddress=self.comboBox.currentText()
        cmd='echo '+actualaddress+'|clip'
        return subprocess.check_call(cmd, shell=True)

    def ga(self):
        address=getaddr.askaddr()
        self.comboBox.addItem(address)
    
    def ref(self):
        actualaddress=self.comboBox.currentText()
        actualcoins=refresh.ref(actualaddress)
        self.label_3.setText(str(actualcoins))

    def send(self):

        amount=self.lineEdit.text()
        dest=self.lineEdit_2.text()

        with open('data/addresslist.txt','r') as f:
            addresses=f.read()
        actualaddress=self.comboBox.currentText()
        pos=addresses.find(actualaddress)
        
        completeaddress=addresses[pos:pos+81]
        print('sending '+amount+' to '+dest+' from '+actualaddress)
        #dì done o error
        ris=mandatx.manda(amount,completeaddress,dest)
        self.label_ok.setText(ris)

        actualaddress=self.comboBox.currentText()
        actualcoins=refresh.ref(actualaddress)
        self.label_3.setText(str(actualcoins))
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
