# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests, subprocess, webbrowser

class Ui_txlist(object):
    def setupUi(self, MainWindow,addr):
        
        MainWindow.setObjectName("ScarletCoin Wallet - Transactions list")

        MainWindow.resize(570, 374)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(420, 130, 111, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 180, 111, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 367, 321))
        self.tableWidget.setObjectName("tableWidget")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 745, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        #self.tableWidget.horizontalHeaderItem(self, 0).setText('ok')

        self.tableWidget.setColumnCount(2)
        #self.tableWidget.setRowCount(0)
        
        with open('data/server.txt','r') as f:
            url=f.read()
        res=requests.post(url,'request_txs'+addr)
        res=res.text.split('#')


        self.tableWidget.setRowCount(len(res))
        row=0
        for e in res:

            txid=e[:32]
            amount=e[e.rfind(':')+1:].strip()
            self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(txid))
            self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(amount))
            row+=1

        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("ScarletCoin Wallet - Transactions list", "ScarletCoin Wallet - Transactions list"))
        self.pushButton.setText(_translate("MainWindow", "Copy txid"))
        self.pushButton_2.setText(_translate("MainWindow", "Lookup on explorer"))
        '''
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "TXID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Amount"))
        '''
        self.tableWidget.setColumnWidth(0,300)
        self.tableWidget.setColumnWidth(1,50)
        self.pushButton.clicked.connect(self.copiatxid)
        self.pushButton_2.clicked.connect(self.apriweb)

    def copiatxid(self):
        #txid=self.tableWidget.currentText()
        txid=self.tableWidget.currentItem().text()
        cmd='echo '+txid+'|clip'
        return subprocess.check_call(cmd, shell=True)

    def apriweb(self):
        with open('data/explorer.txt','r') as f:
            url=f.read()
        webtx=url+self.tableWidget.currentItem().text()+'.html'
        webbrowser.open(webtx)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_txlist()
    addr='0ASSOK6TB39IkKUF'
    ui.setupUi(MainWindow, addr)
    MainWindow.show()
    sys.exit(app.exec_())
